name: AndroidTests

on:
  push:
    branches:
      - main

jobs:
  AndroidTests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"

      - name: Build and run tests
        run: |
          ./gradlew test
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: app/build/test-results

      - name: Display test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: "AndroidTests Test Results"
          report_paths: "**/test-results/*.xml"
